### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by harryyuanfeng** [gsantiago/subtitle.js#9]
when I tried to rung

```
var Subtitle = require('subtitle');
 
var captions = new Subtitle();
 
captions.parse('1.srt');
 
console.log(captions.getSubtitles());

```

i got

```
TypeError: Cannot read property 'match' of undefined
    at Function.Subtitle.toMS (/Users/harryfeng/Downloads/english subtitles/node_modules/subtitle/subtitle.js:153:19)
    at /Users/harryfeng/Downloads/english subtitles/node_modules/subtitle/subtitle.js:81:28
    at Array.forEach (native)
    at Subtitle.parse (/Users/harryfeng/Downloads/english subtitles/node_modules/subtitle/subtitle.js:53:7)
    at Object.<anonymous> (/Users/harryfeng/Downloads/english subtitles/subtitle.js:5:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by romulets** [comment]
Hi, the `parse` method doesn't read a file :/

You should pass the string that you want to parse:

`captions.parse('Hello I will be parsed!');`

**Comment by harryyuanfeng** [comment]
got it.
